### ISSUE TITLE
Add conformance class configuration into the owc10 test.

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-owc10#3]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:
https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
Available conformance classes (testng.xml): 
 * Atom Core
 * Atom WMS

From [ (OGC 12-084r2](http://docs.opengeospatial.org/is/12-084r2/12-084r2.html)
```
In order to conform to this OGC®interface standard, a software implementation shall choose to implement:

a) Conformance to the ‘Core Atom’ encoding.
b) Conformance with zero or more of the offering-specific extensions.
```

`Atom Core` must be configured as basic conformance class

**Comment by lgoltz** [comment]
`Atom Core` was added as basic conformance class. Tested PR #4 locally within docker environment (TEAM Engine 5.2) and the provided atom feed (http://schemas.opengis.net/owc/1.0/examples/sea_ice_extent_01.atom), but there is still the hint that "This test suite does not support the new HTML report and the XML report must be used instead.".

@keshav-nangare  Can you take a look at this?

**Comment by lgoltz** [comment]
Creation of the 'testng' directory was improved (did not work with docker): https://github.com/opengeospatial/ets-owc10/pull/4/commits/8f738fd06aeb840c3e52f82536201a8757e53571, use of properties (https://github.com/opengeospatial/ets-owc10/pull/4/commits/1db104dcab66c25908d4b70a3d0e58f0c8bcdbf5) and ets-common updated to version 9 (https://github.com/opengeospatial/ets-owc10/pull/4/commits/e857852742cba1397ac6ff52d5ae98aa0f309d2b). 
HTML result is shown now and the status of certification is as expected ('no'), tested with the provided atom feed.

**Comment by lgoltz** [comment]
PR https://github.com/opengeospatial/ets-owc10/pull/4

**Comment by dstenger** [comment]
# Functional test

Tested with [teamengine-docker](https://github.com/opengeospatial/teamengine-docker) and file from https://github.com/opengeospatial/ets-owc10/issues/3#issuecomment-372941234.
New HTML report is shown with configured conformance classes.
